#ifndef CCBASICCORE_COMPARES_H
#define CCBASICCORE_COMPARES_H

typedef enum {
	CCBASICCORE_COMPARERESULT_EQUAL,
	CCBASICCORE_COMPARERESULT_SMALLER = -1,
	CCBASICCORE_COMPARERESULT_LARGE = 1
} CompareResult;

#endif